server:
  # 端口 默认8080
  port: 8080
  # path
  context-path: /czy

#spring.mvc.view.prefix: /WEB-INF/jsp/
spring.mvc.view.prefix: /jsp/
spring.mvc.view.suffix: .jsp

# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html

# 属性注入  @ConfigurationProperties(prefix = "home")  前缀
username_new: this is new usernam !



