
server:
  # 端口 默认8080
  port: 8080
  # path
  context-path: /czy

  tomcat:
    # tomcat 编码
    uri-encoding: utf-8
    # 设置内嵌Tomcat的最大线程数
    max-threads: 1000





# 自定义属性与加载
messageValue.message: this is new username !


# 随机字符串
messageValue.value: ${random.value}
# 随机int
messageValue.number: ${random.int}
# 随机long
messageValue.bignumber: ${random.long}
# 10以内的随机数
messageValue.test1: ${random.int(10)}
# 10-20的随机数
messageValue.test2: ${random.int[10,20]}


